### ISSUE TITLE
不支持中文

### ISSUE THREAD

**Issue by transparentumbrella** [Roiocam/V2ray2Clash#2]
如果解析到中文就会报错，能不能解决下

**Comment by Roiocam** [comment]
不太了解你的问题，请贴出你的异常输出，并尽可能提供复现的数据（模拟）？
我已更新配置文件，我这边的节点也是中文的，不太可能无法解析。

**Comment by neo-turak** [comment]
错误内容如下：
[2021.10.24-10:29:06]:已获取规则配置文件
Traceback (most recent call last):
  File "/usr/lib/python3.8/base64.py", line 37, in _bytes_from_decode_data
    return s.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 126-131: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "v2ray.py", line 132, in <module>
    proxy_raw = get_proxies(url)
  File "v2ray.py", line 43, in get_proxies
    vmess_raw = base64.b64decode(raw)
  File "/usr/lib/python3.8/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib/python3.8/base64.py", line 39, in _bytes_from_decode_data
    raise ValueError('string argument should contain only ASCII characters')
ValueError: string argument should contain only ASCII characters

**Comment by Roiocam** [comment]
@Neo-Turak 从报错信息来看，是解析到的 vemss 地址字符串，包含了一些非 ACSCII 编码的字符，我会尝试解决这个问题。
